# Generated by Django 5.1.6 on 2025-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AparecidosVivosNoRegistrados',
            fields=[
                ('numeroRadicado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entidadradica', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreRegional', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreSeccional', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreUnidadBasica', models.CharField(blank=True, max_length=200, null=True)),
                ('usuarioRegistra', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaDesaparicion', models.DateField(blank=True, null=True)),
                ('desaparecido', models.CharField(blank=True, max_length=200, null=True)),
                ('nombreDocumento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('paisDesaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('departamentoDesaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('municipioDesaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('aportanteDatosDesaparecido', models.CharField(blank=True, max_length=200, null=True)),
                ('paisAportanteDatos', models.CharField(blank=True, max_length=100, null=True)),
                ('departamentoAportanteDatos', models.CharField(blank=True, max_length=100, null=True)),
                ('municipioAportanteDatos', models.CharField(blank=True, max_length=100, null=True)),
                ('detalleDireccionAportanteDatos', models.TextField(blank=True, null=True)),
                ('aportanteDatos', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aparecido Vivo No Registrado',
                'verbose_name_plural': 'Aparecidos Vivos No Registrados',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('numero_documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=200)),
                ('nom_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('seccional', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_dependencia', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('documento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('total_casos', models.IntegerField(default=0)),
                ('perfil', models.TextField()),
                ('error', models.TextField(blank=True, null=True)),
                ('tiempo_generacion', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Persona',
                'verbose_name_plural': 'Perfiles de Personas',
            },
        ),
        migrations.CreateModel(
            name='PersonasDf',
            fields=[
                ('numero_identificacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('desaparcion_forzada', models.BooleanField(default=False)),
                ('homicidio', models.BooleanField(default=False)),
                ('secuestro', models.BooleanField(default=False)),
                ('reclutamiento_ilicito', models.BooleanField(default=False)),
                ('rud', models.BooleanField(default=False)),
                ('rud_desaparecido', models.BooleanField(default=False)),
                ('rud_vivo', models.BooleanField(default=False)),
                ('rud_muerto', models.BooleanField(default=False)),
                ('funcionario_FGN', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='RegistroUnicoDesaparecidos',
            fields=[
                ('numero_radicado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento_desaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_desaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio_vereda_desaparicion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_desaparicion', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('edad_1', models.IntegerField(blank=True, null=True)),
                ('edad_2', models.IntegerField(blank=True, null=True)),
                ('estatura_1', models.FloatField(blank=True, null=True)),
                ('estatura_2', models.FloatField(blank=True, null=True)),
                ('ancestro_racial', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_desaparicion', models.CharField(blank=True, choices=[('1.0', 'Desaparecido'), ('2.0', 'Vivo'), ('3.0', 'Muerto')], max_length=100, null=True)),
                ('senales_particulares', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro Unico de Desaparecidos',
                'verbose_name_plural': 'Registros Unicos de Desaparecidos',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoSpoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nunc', models.CharField(max_length=200)),
                ('fecha_hechos', models.DateField(blank=True, null=True)),
                ('fecha_denuncia', models.DateField(blank=True, null=True)),
                ('seccional', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, max_length=300, null=True)),
                ('despacho', models.CharField(blank=True, max_length=500, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=300, null=True)),
                ('relato', models.TextField(blank=True, null=True)),
                ('delito', models.CharField(blank=True, max_length=500, null=True)),
                ('grupo_delito', models.CharField(blank=True, max_length=300, null=True)),
                ('necropsia', models.CharField(blank=True, max_length=200, null=True)),
                ('fuente', models.CharField(blank=True, max_length=200, null=True)),
                ('calidad_vinculado', models.CharField(blank=True, max_length=200, null=True)),
                ('etapa', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Consolidado SPOA',
                'verbose_name_plural': 'Consolidados SPOA',
                'indexes': [models.Index(fields=['nunc'], name='dashboard_c_nunc_a5f8e7_idx'), models.Index(fields=['numero_documento'], name='dashboard_c_numero__2fb418_idx'), models.Index(fields=['fecha_hechos'], name='dashboard_c_fecha_h_774c14_idx'), models.Index(fields=['seccional'], name='dashboard_c_seccion_41b1b6_idx'), models.Index(fields=['unidad'], name='dashboard_c_unidad_1c1283_idx')],
            },
        ),
    ]
