# Generated by Django 5.1.6 on 2025-04-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoSpoa',
            fields=[
                ('nunc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_hechos', models.DateField(blank=True, null=True)),
                ('fecha_denuncia', models.DateField(blank=True, null=True)),
                ('seccional', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('despacho', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('relato', models.TextField(blank=True, null=True)),
                ('delito', models.CharField(blank=True, max_length=200, null=True)),
                ('grupo_delito', models.CharField(blank=True, max_length=200, null=True)),
                ('necropsia', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('calidad_vinculado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Consolidado SPOA',
                'verbose_name_plural': 'Consolidados SPOA',
            },
        ),
        migrations.CreateModel(
            name='PersonasDf',
            fields=[
                ('numero_identificacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('desaparcion_forzada', models.BooleanField(default=False)),
                ('homicidio', models.BooleanField(default=False)),
                ('secuestro', models.BooleanField(default=False)),
                ('reclutamiento_ilicito', models.BooleanField(default=False)),
                ('rud', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='RegistroUnicoDesaparecidos',
            fields=[
                ('numero_radicado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento_desaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio_desaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio_vereda_desaparicion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_desaparicion', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('edad_1', models.IntegerField(blank=True, null=True)),
                ('edad_2', models.IntegerField(blank=True, null=True)),
                ('estatura_1', models.FloatField(blank=True, null=True)),
                ('estatura_2', models.FloatField(blank=True, null=True)),
                ('ancestro_racial', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_desaparicion', models.CharField(blank=True, max_length=100, null=True)),
                ('senales_particulares', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro Unico de Desaparecidos',
                'verbose_name_plural': 'Registros Unicos de Desaparecidos',
            },
        ),
    ]
